title: sbfksmq-Blog
description: "sbfksmq github log"
author:
  name: "sbfksmq"
  email: "sbfksmq@outlook.com"
  url: "https://sbfksmq.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "sbfksmq"
year : "2023"
